package CommerceApp;
import Adapters.JDBCAdapter;
import java.awt.AWTEvent;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import util.Operation;
import util.Utilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class customerSells extends javax.swing.JDialog {
    
    /**
     * variables privées et public du programme
     */
    private ChoiceWindow customerChoice;
    private String venteSQL = "SELECT IDA, D, T, MODE, TOTAL"
                        + " FROM vente INNER JOIN client"
                        + " ON vente.ID = client.ID"
                        + " WHERE client.NOM = ";
    private String venteDetailSQL =
                        "SELECT DESIG, QTEA, QTUA, lvente.PRIXA,"
                        + " QTEA* QTUA * lvente.PRIXA as Montant"
                        + " FROM lvente INNER JOIN vente INNER JOIN produit"
                        + " ON vente.IDA = lvente.IDA AND lvente.IDP = produit.IDP"
                        + " WHERE lvente.IDA =";
    private JDBCAdapter dataTable;
    private JDBCAdapter dataTable2;
    /**
     * Creates new form customerSells
     */
    public customerSells(JFrame frm) {
        super(frm,true);
        initComponents();
        customerChoice = new ChoiceWindow(Operation.CUSTOMER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clientTextField = new javax.swing.JTextField();
        customerSearchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerSellsTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        customerSellsDetailTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        clientSoldeTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombreEnregistrementTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nombreEnregistrementTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        selectedRowLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clientTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clientTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                clientTextFieldKeyTyped(evt);
            }
        });
        getContentPane().add(clientTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 290, -1));

        customerSearchButton.setText("Chercher");
        customerSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerSearchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(customerSearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 11, -1, -1));

        customerSellsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(customerSellsTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, 990, 170));

        customerSellsDetailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(customerSellsDetailTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 990, 245));

        jLabel2.setBackground(new java.awt.Color(0, 0, 204));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ventes des clients");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 0, 610, 79));
        getContentPane().add(clientSoldeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 40, 213, -1));

        jLabel1.setText("Credit dû");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 43, -1, -1));

        jLabel3.setText("Nombre d'enregistrement");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 560, 160, 20));

        nombreEnregistrementTextField1.setEditable(false);
        nombreEnregistrementTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        nombreEnregistrementTextField1.setText("00.00");
        getContentPane().add(nombreEnregistrementTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 263, 102, -1));

        jLabel4.setText("Nombre d'enregistrement");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 266, 160, -1));

        nombreEnregistrementTextField2.setEditable(false);
        nombreEnregistrementTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        nombreEnregistrementTextField2.setText("00.00");
        getContentPane().add(nombreEnregistrementTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 560, 102, -1));

        jLabel5.setText("Selected Row : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, -1, -1));

        selectedRowLabel.setText("0");
        getContentPane().add(selectedRowLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clientTextFieldKeyPressed
        processKeyPressed(evt);
    }//GEN-LAST:event_clientTextFieldKeyPressed

    private void customerSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerSearchButtonActionPerformed
        processButtonActionPerformed(evt);
    }//GEN-LAST:event_customerSearchButtonActionPerformed

    private void clientTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clientTextFieldKeyTyped
        processKeyTyped(evt);
    }//GEN-LAST:event_clientTextFieldKeyTyped

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        processWindowGainedFocus(evt);
    }//GEN-LAST:event_formWindowGainedFocus

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField clientSoldeTextField;
    private javax.swing.JTextField clientTextField;
    private javax.swing.JButton customerSearchButton;
    private javax.swing.JTable customerSellsDetailTable;
    private javax.swing.JTable customerSellsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nombreEnregistrementTextField1;
    private javax.swing.JTextField nombreEnregistrementTextField2;
    private javax.swing.JLabel selectedRowLabel;
    // End of variables declaration//GEN-END:variables

    private void processKeyPressed(KeyEvent e) {
        if (e.getKeyCode() == KeyEvent.VK_ENTER){
            processButtonActionPerformed(e);
        }
    }

    private void processButtonActionPerformed(AWTEvent e) {
        if ((e.getSource() == clientTextField)
            ||(e.getSource() == customerSearchButton)){
            customerChoice.show(clientTextField.getLocationOnScreen().x, 
                                clientTextField.getLocationOnScreen().y + clientTextField.getHeight(), 
                                clientTextField.getWidth(), 
                                clientTextField.getText());
        }
    }

    private void processKeyTyped(KeyEvent evt) {
        int keyCode = evt.getKeyCode();
        char keyChar = evt.getKeyChar();
        if (Character.isLowerCase(keyChar)) {
            evt.setKeyChar(Character.toUpperCase(keyChar));
        }
    }

    private void processWindowGainedFocus(WindowEvent evt) {
                ArrayList<Object> result = customerChoice.getResult(); 
	try{
            if (result.size() != 0){
                            clientTextField.setText((String)result.get(0));
                            clientSoldeTextField.setText (result.get(1).toString());
                            processSellsSearch(clientTextField.getText());
            }
	}catch(NullPointerException ex){}
    }

    private void processSellsSearch(String text) {
        dataTable = new JDBCAdapter(Utilities.URL,Utilities.DRIVER_NAME,
                                    Utilities.USER, Utilities.PASSWORD); 
        dataTable.executeQuery(venteSQL + "'" + clientTextField.getText() + "'");
        customerSellsTable.setModel(dataTable);
        nombreEnregistrementTextField1.setText(Integer.toString(dataTable.getRowCount()));
        customerSellsTable.repaint();
        customerSellsTable.requestFocusInWindow();
        customerSellsTable.changeSelection(0, 0, false, false);
        processRelatedSearch((int)customerSellsTable.getValueAt(0, 0));
        ListSelectionModel rowSM = customerSellsTable.getSelectionModel();
            rowSM.addListSelectionListener(new ListSelectionListener() {
                public void valueChanged(ListSelectionEvent e) {
                    //Ignore extra messages.
                    if (e.getValueIsAdjusting()) return;

                    ListSelectionModel lsm = (ListSelectionModel)e.getSource();
                    if (lsm.isSelectionEmpty()) {
                        System.out.println("No rows are selected.");
                    } else {
                        int selectedRow = lsm.getMinSelectionIndex();
                        selectedRowLabel.setText("Row " + selectedRow
                                           + " is now selected.");
                        processRelatedSearch((int)customerSellsTable.getValueAt(selectedRow, 0));
                    }
                }
            });
    }

    private void processRelatedSearch(int i) {
        dataTable2 = new JDBCAdapter(Utilities.URL,Utilities.DRIVER_NAME,
                                    Utilities.USER, Utilities.PASSWORD); 
        dataTable2.executeQuery(venteDetailSQL + "'" + i + "'");
        nombreEnregistrementTextField2.setText(Integer.toString(dataTable2.getRowCount()));
        customerSellsDetailTable.setModel(dataTable2);
        customerSellsDetailTable.getColumnModel().getColumn(0)
                                .setPreferredWidth(350);
        customerSellsDetailTable.repaint();
    }
}
