/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CommerceApp;

import Adapters.FrameAdapter;
import Adapters.JDBCAdapter;
import static CommerceApp.FenetrePrincipale.parentFrame;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JFrame;
import util.FileProcess;
import util.Operation;

/**
 *
 * @author DELL
 */
public class RechercheOperationnel extends javax.swing.JDialog {
    private Operation operation;
    private FileProcess fileProcess;
    private ChoiceWindow choiceWindow;
    private String result;
    private JFrame parentFrame;
    private JDialog parentDialog;
    /**
     * Creates new form rechercheOperationnel
     */
    public RechercheOperationnel(JFrame frm, Operation op, FileProcess fp) {
        super(frm, true);
        parentFrame = frm;
        operation = op;
        fileProcess = fp;
        choiceWindow = new ChoiceWindow(op);
        initComponents();
        titleLabel.setText(titleLabel.getText() + " " +
                        op.getFrameTitle() + " " +
                        fp.getProcessTitle());        
        rechercheLabel.setText(rechercheLabel.getText() + " "
                                + operation.getFrameTitle().toLowerCase());
        titleLabel.setText(titleLabel.getText() + " " 
                             +operation.getFrameTitle());
        this.setPreferredSize(new Dimension(
                rechercheLabel.getPreferredSize().width + 50,
                this.getPreferredSize().height));
        parentDialog = this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rechercheTextField = new javax.swing.JTextField();
        rechercheLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        rechercheTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercheTextFieldActionPerformed(evt);
            }
        });
        rechercheTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rechercheTextFieldKeyTyped(evt);
            }
        });

        rechercheLabel.setText("rechercher");

        titleLabel.setBackground(new java.awt.Color(0, 0, 0));
        titleLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(204, 0, 0));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("RECHERCHE");
        titleLabel.setOpaque(true);

        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        okButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                okButtonKeyPressed(evt);
            }
        });

        cancelButton.setText("Annuler");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rechercheLabel)
                        .addGap(18, 18, 18)
                        .addComponent(rechercheTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addGap(29, 29, 29)
                        .addComponent(okButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rechercheLabel)
                    .addComponent(rechercheTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rechercheTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rechercheTextFieldKeyTyped
        char keyChar = evt.getKeyChar();
        if (Character.isLowerCase(keyChar)) {
            evt.setKeyChar(Character.toUpperCase(keyChar));
        }
    }//GEN-LAST:event_rechercheTextFieldKeyTyped

    private void rechercheTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercheTextFieldActionPerformed
        choiceWindow.show(0, 
                          rechercheTextField.getHeight(), 
                          rechercheTextField.getWidth(), 
                          rechercheTextField.getText());
    }//GEN-LAST:event_rechercheTextFieldActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        runOperationProcess();
    }//GEN-LAST:event_okButtonActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        try{
            if (choiceWindow.getResult().size() != 0){
                result = (String)choiceWindow.getResult().get(0);
                rechercheTextField.setText(result);
                okButton.requestFocusInWindow();
            }
        }catch(NullPointerException ex){
            System.err.println(" y a pas moyen ...!");
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void okButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_okButtonKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            runOperationProcess();
        }
    }//GEN-LAST:event_okButtonKeyPressed

    public String getResult(){
        return result;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel rechercheLabel;
    private javax.swing.JTextField rechercheTextField;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

    private void runOperationProcess() {
        switch(operation){
            case PRODUCT:
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {        
                        OperateProductDialog f = new OperateProductDialog(
                                                            parentFrame,
                                                            fileProcess, 
                                                            result);
                        f.setVisible(true);                        
                    }       
                });
            break;
            case PROVIDER:
            case CUSTOMER:
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        switch(fileProcess){
                            case MODIFY:
                                ModifyOperatorDialog f = new ModifyOperatorDialog(
                                        parentFrame,
                                        operation,
                                        result
                                );
                                f.setVisible(true);
                            break;
                            case DELETE:
                                DeleteOperatorDialog ff = new DeleteOperatorDialog(
                                        parentFrame,
                                        operation,
                                        FileProcess.DELETE,
                                        result
                                );
                                ff.setVisible(true);
                            break;
                            case CONSULT:
                                OperatorDialog dialog = new OperatorDialog(parentFrame,
                                    operation,
                                    FileProcess.CONSULT);
                                String query = "SELECT ID, NOM , ADR, WILAYA, NRC,"
                                + "NFI, NAR, TEL1, TEL2, TEL3, FAX, EMAIL, WEB,"
                                + "(SOLDE2 + SOLDE) AS CREDIT, OBS FROM " + operation.getTableName()
                                + " WHERE NOM='" + result + "'";
                                JDBCAdapter operator = dialog.getJDBCAdapter(query);
                                dialog.updateFields(operator);
                                dialog.setVisible(true);
                            break;
                        }
                    }
                });
            break;
        }
        dispose();
    }

    
}
